version: '3.9'
services:
  app:
    restart: always
    build: ./server
    environment:
      - DATABASE_HOST=mongodb://mongodb:27017/league_stats_app?authSource=admin
    ports:
      - '3001:3001'
    depends_on:
      - mongodb
    networks:
      frontend:
      backend:
  mongodb:
    image: mongo:4.4
    volumes:
      - ./data/mongo:/data/db
    networks:
      backend:
  front:
    build: ./client
    ports:
      - '3000:3000'
    depends_on:
      - app
    stdin_open: true
    tty: true
    networks:
      frontend:

networks:
  frontend:
  backend:
